### ISSUE TITLE
LFQ phospho data analysis 

### ISSUE THREAD

**Issue by solabthomas** [Vitek-Lab/MSstatsPTM#88]
Is there any workflow or codes to support LFQ phospho generated from fragpipe. As there is only fragpipe TMT phospho workflow in the examples

**Comment by tonywu1999** [comment]
Hi,

For the function `FragPipetoMSstatsPTMFormat`, you can set the parameter `label_type` to "LF".  

I don't see any examples for LF in the vignettes though.  If you have any example datasets from Fragpipe with PTMs, we could add those examples to the vignettes.  Otherwise, our team will look to find a dataset ourselves.

**Comment by solabthomas** [comment]
Hi, thanks for your reply. Yes, I have the generated files and output from LFQ phospho workflow, can I send it to your email account? 

Thanks.

**Comment by tonywu1999** [comment]
@solabthomas 

Yes, you can send it to my northeastern email - ant.wu@northeastern.edu

Thanks,
Tony

**Comment by tonywu1999** [comment]
Closing in favor of https://github.com/Vitek-Lab/MSstatsPTM/pull/90
