### ISSUE TITLE
how to get maxq_tmt_annotation 

### ISSUE THREAD

**Issue by gaoxiangcao** [Vitek-Lab/MSstatsPTM#89]
hi，
i want to know how to get the maxq_tmt_annotation file？

**Comment by tonywu1999** [comment]
Hi,

Did you load the MSstatsPTM package into your workspace?  After loading the MSstatsPTM, you should be able to run the following command to view the first few rows:

```
library(MSstatsPTM)
head(maxq_tmt_annotation)
```

**Comment by gaoxiangcao** [comment]
Yes, I have downloaded it. But what I want to know is whether the maxq_tmt_annotation file was generated using the evidence file, or is there a specific function to process it? Is this a required step for format conversion?

**Comment by tonywu1999** [comment]
Hi @gaoxiangcao 

Below are my responses to your questions.  Let me know if you have any additional questions.

> But what I want to know is whether the maxq_tmt_annotation file was generated using the evidence file, or is there a specific function to process it?

The user of our package is responsible for creating the annotation file by hand.  There's no specific function to auto-generate annotation files at the moment.

> Is this a required step for format conversion?

This is a required step because in order to perform differential abundance analysis, each run needs to be annotated with BioReplicate & Condition information (additionally Mixture information in the case of TMT).   Annotation information allows for the application of statistical tests to determine the significance of observed differences in abundance between conditions.
